import type { Place } from "./types";

const destinationImage = (id: string) => `/assets/img/destinations/${id}.jpg`;

export const places: Place[] = [
  { id: "burnham-park", name: "Burnham Park", kind: "park", area: "City Center", lat: 16.41107, lng: 120.59334, duration: 75, image: destinationImage("burnham-park"), popular: true, price: "Budget", description: "Baguio's central lake park—an easy first stop for boats, bikes, gardens, and an unhurried walk.", tags: ["nature", "family", "walkable"] },
  { id: "botanical-garden", name: "Baguio Botanical Garden", kind: "park", area: "East Baguio", lat: 16.42194, lng: 120.61335, duration: 90, image: destinationImage("botanical-garden"), popular: true, price: "Budget", description: "A landscaped cultural garden with Cordilleran features, greenery, art, and photo-friendly paths.", tags: ["nature", "culture", "photos"] },
  { id: "wright-park", name: "Wright Park", kind: "park", area: "East Baguio", lat: 16.42011, lng: 120.61917, duration: 75, image: destinationImage("wright-park"), popular: true, price: "Budget", description: "A pine-lined promenade beside The Mansion, with the Pool of Pines and horseback-riding area.", tags: ["nature", "family", "classic"] },
  { id: "mines-view-park", name: "Mines View Park", kind: "park", area: "East Baguio", lat: 16.42492, lng: 120.62771, duration: 75, image: destinationImage("mines-view-park"), popular: true, price: "Budget", description: "A classic mountain viewpoint with Cordillera scenery, local snacks, and souvenir stalls.", tags: ["views", "souvenirs", "classic"] },
  { id: "camp-john-hay", name: "Camp John Hay", kind: "park", area: "South Baguio", lat: 16.39784, lng: 120.61137, duration: 150, image: destinationImage("camp-john-hay"), popular: true, price: "Mid-range", description: "A broad pine-covered estate with forest trails, heritage sites, cafés, and recreation areas.", tags: ["nature", "heritage", "long visit"] },
  { id: "mirador-heritage-eco-park", name: "Mirador Heritage & Eco Park", kind: "park", area: "West Baguio", lat: 16.40945, lng: 120.57863, duration: 105, image: destinationImage("mirador-heritage-eco-park"), popular: true, price: "Budget", description: "A hillside heritage park known for gardens, contemplative spaces, art, and sunset views.", tags: ["views", "gardens", "sunset"] },
  { id: "tam-awan-village", name: "Tam-awan Village", kind: "park", area: "West Baguio", lat: 16.429, lng: 120.57785, duration: 105, image: destinationImage("tam-awan-village"), popular: true, price: "Budget", description: "An artists' village with Cordilleran-inspired houses, galleries, workshops, and hillside paths.", tags: ["arts", "culture", "hillside"] },
  { id: "igorot-stone-kingdom", name: "Igorot Stone Kingdom", kind: "park", area: "West Baguio", lat: 16.4238, lng: 120.5727, duration: 105, image: destinationImage("igorot-stone-kingdom"), popular: true, price: "Mid-range", description: "A large stone-terrace attraction inspired by Cordilleran themes and mountain architecture.", tags: ["culture", "architecture", "family"] },
  { id: "bencab-museum", name: "BenCab Museum", kind: "park", area: "Tuba / Asin", lat: 16.3814, lng: 120.5503, duration: 150, image: destinationImage("bencab-museum"), popular: true, price: "Mid-range", description: "Contemporary art, Cordilleran collections, gardens, and mountain views along Asin Road.", tags: ["arts", "museum", "culture"] },
  { id: "strawberry-farm", name: "La Trinidad Strawberry Farm", kind: "park", area: "La Trinidad", lat: 16.4549, lng: 120.5897, duration: 105, image: destinationImage("strawberry-farm"), popular: true, price: "Budget", description: "A seasonal farm visit for strawberry picking, produce, snacks, and local stalls.", tags: ["food", "farm", "family"] },
  { id: "museo-kordilyera", name: "Museo Kordilyera", kind: "park", area: "City Center", lat: 16.4028, lng: 120.5918, duration: 75, image: destinationImage("museo-kordilyera"), price: "Budget", description: "A university museum focused on Cordilleran peoples, arts, histories, and material culture.", tags: ["culture", "museum", "indoors"] },
  { id: "baguio-cathedral", name: "Baguio Cathedral", kind: "park", area: "City Center", lat: 16.41466, lng: 120.59885, duration: 35, image: destinationImage("baguio-cathedral"), price: "Free", description: "A rose-colored hilltop landmark overlooking Session Road and the city center.", tags: ["heritage", "views", "walkable"] },

  { id: "cafe-by-the-ruins", name: "Café by the Ruins", kind: "restaurant", area: "City Center", lat: 16.4122, lng: 120.5907, duration: 75, popular: true, price: "Mid-range", description: "A long-running Baguio dining name with a menu inspired by local produce and mountain flavors.", tags: ["Filipino", "local ingredients", "brunch"] },
  { id: "oh-my-gulay", name: "Oh My Gulay", kind: "restaurant", area: "Session Road", lat: 16.4141, lng: 120.5974, duration: 75, popular: true, price: "Budget", description: "A creative, art-filled vegetarian restaurant tucked above Session Road.", tags: ["vegetarian", "arts", "city center"] },
  { id: "hill-station", name: "Hill Station", kind: "restaurant", area: "Upper Session", lat: 16.4115, lng: 120.6003, duration: 90, popular: true, price: "Premium", description: "A heritage-setting restaurant for leisurely meals near the top of Session Road.", tags: ["heritage", "date night", "international"] },
  { id: "farmers-daughter", name: "Farmer's Daughter", kind: "restaurant", area: "Tam-awan", lat: 16.4295, lng: 120.5773, duration: 75, popular: true, price: "Mid-range", description: "A casual stop associated with hearty Cordilleran dishes near Tam-awan Village.", tags: ["Cordilleran", "local", "casual"] },
  { id: "lemon-and-olives", name: "Lemon and Olives", kind: "restaurant", area: "Outlook Drive", lat: 16.4276, lng: 120.6201, duration: 90, price: "Mid-range", description: "A relaxed Greek-inspired option in the greener, quieter side of the city.", tags: ["Greek", "group dining", "views"] },
  { id: "chaya", name: "Chaya", kind: "restaurant", area: "Legarda Road", lat: 16.4046, lng: 120.5918, duration: 90, price: "Premium", description: "An intimate Japanese dining option suited to a slower evening meal.", tags: ["Japanese", "dinner", "quiet"] },

  { id: "the-manor", name: "The Manor at Camp John Hay", kind: "hotel", area: "Camp John Hay", lat: 16.3949, lng: 120.6136, duration: 30, popular: true, price: "Premium", description: "A classic mountain hotel experience set among Camp John Hay's pine trees.", tags: ["pine views", "resort", "family"] },
  { id: "forest-lodge", name: "The Forest Lodge", kind: "hotel", area: "Camp John Hay", lat: 16.397, lng: 120.6126, duration: 30, price: "Premium", description: "A family-friendly Camp John Hay base with easy access to the estate's attractions.", tags: ["family", "pine views", "resort"] },
  { id: "g1-lodge", name: "G1 Lodge", kind: "hotel", area: "City Center", lat: 16.4086, lng: 120.6007, duration: 30, price: "Mid-range", description: "A central stay within convenient walking distance of Session Road and SM Baguio.", tags: ["central", "walkable", "modern"] },
  { id: "microtel-baguio", name: "Microtel by Wyndham Baguio", kind: "hotel", area: "Upper Session", lat: 16.4048, lng: 120.5994, duration: 30, price: "Mid-range", description: "A practical city base beside the bus terminal area and near central attractions.", tags: ["transport access", "central", "practical"] },
  { id: "grand-sierra-pines", name: "Grand Sierra Pines", kind: "hotel", area: "Outlook Drive", lat: 16.4282, lng: 120.6192, duration: 30, price: "Premium", description: "A quieter mountain stay near Wright Park, The Mansion, and Mines View.", tags: ["quiet", "pine views", "east Baguio"] },
  { id: "venus-parkview", name: "Venus Parkview Hotel", kind: "hotel", area: "Burnham", lat: 16.409, lng: 120.5918, duration: 30, price: "Mid-range", description: "A central option close to Burnham Park and the public market.", tags: ["Burnham", "central", "family"] }
];

export const parks = places.filter((place) => place.kind === "park");
export const restaurants = places.filter((place) => place.kind === "restaurant");
export const hotels = places.filter((place) => place.kind === "hotel");
export const featuredRestaurants = restaurants.slice(0, 4);

export const getPlace = (id: string) => places.find((place) => place.id === id);
